### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by elliot710** [Ph3nol/Trading-Bot#3]
Can't get it working with root or normal user...
![image](https://user-images.githubusercontent.com/49530492/110528192-8a0d5c00-8120-11eb-9c31-564dde38da60.png)

**Comment by Ph3nol** [comment]
Hum, I can see you doing `chmod +x /usr/bin/bot`. Bot shell script is downloaded into `/usr/local/bin/bot` (not `/usr/bin/bot`). You can move it if necessary for you, or make a symlink.

**Comment by Ph3nol** [comment]
I also have an idea about your cURL error.
I will update the install script to use `/usr/local/bin/bot` only if exists (not your case), `/usr/bin/bot` if not.
I'll push this update in a few minutes.

**Comment by Ph3nol** [comment]
Done! ✅ 
https://github.com/Ph3nol/Trading-Bot/commit/578783ee3e8018d3a7cd3b208d2c9d531f0acff9

Can you check? Thank you!

**Comment by elliot710** [comment]
So I just tried on a different machine, still fails on last curl command. (Kubuntu)  Worked ok first time on Mac
![image](https://user-images.githubusercontent.com/49530492/110541073-ec218d80-812f-11eb-8fd0-233219fff783.png)

**Comment by elliot710** [comment]
Sorry to bother you,  just trying to get it installed. seems easy but idk why it fails

**Comment by Ph3nol** [comment]
Hum, strange.

**Comment by Ph3nol** [comment]
![image](https://user-images.githubusercontent.com/183984/110541781-7fef5b80-8128-11eb-8a75-4ac907d6f959.png)

OK for me from OSX, Ubutnu, Debian and Alpine.

**Comment by elliot710** [comment]
I checked the source code and I can't understand what I'm doing wrong, so I created a fresh google cloud instance, same thing. Maybe there's a dependency or precondition. Also theoretically should be ok with a regular user
![image](https://user-images.githubusercontent.com/49530492/110547228-54746d00-8138-11eb-9fd9-57fa273f0c2c.png)

**Comment by elliot710** [comment]
![image](https://user-images.githubusercontent.com/49530492/110550190-e16cf580-813b-11eb-931d-06d1283d18ca.png)
I do not find problems they find me :D

**Comment by Ph3nol** [comment]
Oops! This problem is identified. Scripts should be synced with host (host runs Docker instances which use them).
I'll fix it ASAP. Sorry about this!

**Comment by Ph3nol** [comment]
I've updated the install script. Can you check? Thank you!

**Comment by elliot710** [comment]
![image](https://user-images.githubusercontent.com/49530492/110616187-f0d05b00-819c-11eb-997b-2f33ba9d318d.png)

**Comment by Ph3nol** [comment]
Oops! Updated! 😅

**Comment by elliot710** [comment]
Ok, now it worked. Next question: To access UI, I just need to add cors domain and point it to server's IP? If I have multiple bot instances, wouldn't all containers point to server:80?

**Comment by Ph3nol** [comment]
In fact, 2 solutions :
- 1 UI for multiple Instances (but 1 Session, so logout to check another instance is required)
- 1 UI for 1 instance (so 1 port by UI instance), allows us to have multiple UI/Instances simultaneously (chosen solution for this Trading Bot)
![image](https://user-images.githubusercontent.com/183984/110634659-832b2b80-81aa-11eb-96e7-3dffcb68b822.png)

Each UI is available from `bot status`. Just click on "UI"! 😉

**Comment by Ph3nol** [comment]
Let's continue here for this point: https://github.com/Ph3nol/Trading-Bot/issues/2#issuecomment-795396381
